<?php

declare(strict_types=1);

$opcoes_meses = [
    ['valor' => 1, 'rotulo' => 'Janeiro'],
    ['valor' => 2, 'rotulo' => 'Fevereiro'],
    ['valor' => 3, 'rotulo' => 'Marco'],
    ['valor' => 4, 'rotulo' => 'Abril'],
    ['valor' => 5, 'rotulo' => 'Maio'],
    ['valor' => 6, 'rotulo' => 'Junho'],
    ['valor' => 7, 'rotulo' => 'Julho'],
    ['valor' => 8, 'rotulo' => 'Agosto'],
    ['valor' => 9, 'rotulo' => 'Setembro'],
    ['valor' => 10, 'rotulo' => 'Outubro'],
    ['valor' => 11, 'rotulo' => 'Novembro'],
    ['valor' => 12, 'rotulo' => 'Dezembro'],
];

$entidades = [
    'usuarios' => [
        'titulo' => 'Usuarios',
        'singular' => 'usuario',
        'secao' => 'usuarios',
        'perfis' => ['ADMIN'],
        'tabela' => 'Usuario',
        'id' => 'idUsuario',
        'ordem' => 'idUsuario DESC',
        'campos' => [
            ['nome' => 'nome', 'rotulo' => 'Nome', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'sobrenome', 'rotulo' => 'Sobrenome', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'cpf', 'rotulo' => 'CPF', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'email', 'rotulo' => 'E-mail', 'tipo' => 'email', 'obrigatorio' => true],
            ['nome' => 'telefone', 'rotulo' => 'Telefone', 'tipo' => 'tel', 'obrigatorio' => true],
            ['nome' => 'senhaCriptografada', 'rotulo' => 'Senha', 'tipo' => 'password', 'obrigatorio' => true, 'tabela_listagem' => false],
            ['nome' => 'perfil', 'rotulo' => 'Perfil', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => ['ADMIN', 'GERENTE', 'ATENDENTE', 'CLIENTE']],
        ],
    ],
    'academias' => [
        'titulo' => 'Academias',
        'singular' => 'academia',
        'secao' => 'academias',
        'perfis' => ['ADMIN'],
        'tabela' => 'Academia',
        'id' => 'idAcademia',
        'ordem' => 'idAcademia DESC',
        'campos' => [
            ['nome' => 'nome', 'rotulo' => 'Nome', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'cnpj', 'rotulo' => 'CNPJ', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'telefone', 'rotulo' => 'Telefone', 'tipo' => 'tel', 'obrigatorio' => true],
            ['nome' => 'endereco', 'rotulo' => 'Endereco', 'tipo' => 'text', 'obrigatorio' => true, 'completo' => true],
        ],
    ],
    'alunos' => [
        'titulo' => 'Alunos',
        'singular' => 'aluno',
        'secao' => 'alunos',
        'perfis' => ['ADMIN', 'ATENDENTE', 'GERENTE'],
        'somente_leitura_perfis' => ['GERENTE'],
        'tabela' => 'Aluno',
        'id' => 'idAluno',
        'ordem' => 'idAluno DESC',
        'campos' => [
            ['nome' => 'nome', 'rotulo' => 'Nome', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'responsavelCadastro', 'rotulo' => 'Responsavel pelo cadastro', 'tipo' => 'text', 'virtual' => true, 'somente_leitura' => true, 'apenas_novo' => true, 'tabela_listagem' => false, 'ocultar_para_perfis' => ['ADMIN', 'GERENTE']],
            ['nome' => 'senhaCliente', 'rotulo' => 'Senha do cliente', 'tipo' => 'password', 'obrigatorio' => true, 'virtual' => true, 'apenas_novo' => true, 'tabela_listagem' => false, 'ocultar_para_perfis' => ['ADMIN', 'GERENTE']],
            ['nome' => 'idUsuario', 'rotulo' => 'Usuario de acesso', 'tipo' => 'select', 'ocultar_para_perfis' => ['ATENDENTE'], 'relacao' => ['tabela' => 'Usuario', 'id' => 'idUsuario', 'rotulo' => "CONCAT(nome, ' ', sobrenome, ' (', email, ')')", 'filtro' => "perfil = 'CLIENTE' AND idUsuario NOT IN (SELECT idUsuario FROM Aluno WHERE idUsuario IS NOT NULL)"]],
            ['nome' => 'cpf', 'rotulo' => 'CPF', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'telefone', 'rotulo' => 'Telefone', 'tipo' => 'tel', 'obrigatorio' => true],
            ['nome' => 'email', 'rotulo' => 'E-mail', 'tipo' => 'email', 'obrigatorio' => true],
            ['nome' => 'dataNascimento', 'rotulo' => 'Data de nascimento', 'tipo' => 'date', 'obrigatorio' => true],
            ['nome' => 'idAcademia', 'rotulo' => 'Academia', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Academia', 'id' => 'idAcademia', 'rotulo' => 'nome']],
            ['nome' => 'planoAluno', 'rotulo' => 'Plano escolhido', 'tipo' => 'select', 'obrigatorio' => true, 'virtual' => true, 'apenas_novo' => true, 'tabela_listagem' => false, 'ocultar_para_perfis' => ['ADMIN', 'GERENTE'], 'opcoes' => [
                ['valor' => 'Basico', 'rotulo' => 'Basico - gratuito'],
                ['valor' => 'Maromba', 'rotulo' => 'Maromba - R$ 49,90'],
                ['valor' => 'Shape', 'rotulo' => 'Shape - R$ 99,99'],
            ]],
        ],
    ],
    'matriculas' => [
        'titulo' => 'Matriculas',
        'singular' => 'matricula',
        'secao' => 'matriculas',
        'perfis' => ['ADMIN', 'ATENDENTE', 'GERENTE'],
        'somente_leitura_perfis' => ['GERENTE'],
        'cadastro_manual' => false,
        'tabela' => 'Matricula',
        'id' => 'idMatricula',
        'ordem' => 'idMatricula DESC',
        'campos' => [
            ['nome' => 'codigoMatricula', 'rotulo' => 'Codigo da matricula', 'tipo' => 'text', 'somente_leitura' => true, 'ajuda' => 'Gerado automaticamente para cada matricula.'],
            ['nome' => 'dataMatricula', 'rotulo' => 'Data da matricula', 'tipo' => 'date', 'obrigatorio' => true],
            ['nome' => 'status', 'rotulo' => 'Status', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => ['Ativa', 'Cancelada', 'Trancada']],
            ['nome' => 'plano', 'rotulo' => 'Plano', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => [
                ['valor' => 'Basico', 'rotulo' => 'Basico - gratuito'],
                ['valor' => 'Maromba', 'rotulo' => 'Maromba - R$ 49,90'],
                ['valor' => 'Shape', 'rotulo' => 'Shape - R$ 99,99'],
            ]],
            ['nome' => 'valorPlano', 'rotulo' => 'Valor do plano', 'tipo' => 'number', 'somente_leitura' => true, 'dinheiro' => true, 'ajuda' => 'Preenchido automaticamente conforme o plano.'],
            ['nome' => 'idAluno', 'rotulo' => 'Aluno', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Aluno', 'id' => 'idAluno', 'rotulo' => 'nome']],
            ['nome' => 'idAcademia', 'rotulo' => 'Academia', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Academia', 'id' => 'idAcademia', 'rotulo' => 'nome']],
            ['nome' => 'idAtendente', 'rotulo' => 'Atendente', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Usuario', 'id' => 'idUsuario', 'rotulo' => "CONCAT(nome, ' ', sobrenome)", 'filtro' => "perfil = 'ATENDENTE'"]],
        ],
    ],
    'mensalidades' => [
        'titulo' => 'Mensalidades',
        'singular' => 'mensalidade',
        'secao' => 'mensalidades',
        'perfis' => ['ADMIN', 'ATENDENTE', 'GERENTE'],
        'somente_leitura_perfis' => ['GERENTE'],
        'cadastro_manual' => false,
        'tabela' => 'Mensalidade',
        'id' => 'idMensalidade',
        'ordem' => 'idMensalidade DESC',
        'campos' => [
            ['nome' => 'valor', 'rotulo' => 'Valor', 'tipo' => 'number', 'somente_leitura' => true, 'dinheiro' => true, 'ajuda' => 'Valor calculado pelo plano da matricula escolhida.'],
            ['nome' => 'dataVencimento', 'rotulo' => 'Data de vencimento', 'tipo' => 'date', 'obrigatorio' => true],
            ['nome' => 'dataPagamento', 'rotulo' => 'Data de pagamento', 'tipo' => 'date'],
            ['nome' => 'status', 'rotulo' => 'Status', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => ['Pendente', 'Pago', 'Atrasado']],
            ['nome' => 'idMatricula', 'rotulo' => 'Matricula', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Matricula', 'id' => 'idMatricula', 'rotulo' => "CONCAT(codigoMatricula, ' - aluno ', idAluno, ' - ', plano)"]],
        ],
    ],
    'receitas' => [
        'titulo' => 'Receitas',
        'singular' => 'receita',
        'secao' => 'receitas',
        'perfis' => ['GERENTE'],
        'tabela' => 'Receita',
        'id' => 'idReceita',
        'ordem' => 'idReceita DESC',
        'campos' => [
            ['nome' => 'descricao', 'rotulo' => 'Descricao', 'tipo' => 'textarea', 'obrigatorio' => true, 'completo' => true],
            ['nome' => 'valor', 'rotulo' => 'Valor', 'tipo' => 'number', 'obrigatorio' => true, 'dinheiro' => true],
            ['nome' => 'dataReceita', 'rotulo' => 'Data da receita', 'tipo' => 'date', 'obrigatorio' => true],
            ['nome' => 'idAcademia', 'rotulo' => 'Academia', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Academia', 'id' => 'idAcademia', 'rotulo' => 'nome']],
        ],
    ],
    'despesas' => [
        'titulo' => 'Despesas',
        'singular' => 'despesa',
        'secao' => 'despesas',
        'perfis' => ['GERENTE'],
        'tabela' => 'Despesa',
        'id' => 'idDespesa',
        'ordem' => 'idDespesa DESC',
        'campos' => [
            ['nome' => 'descricao', 'rotulo' => 'Descricao', 'tipo' => 'textarea', 'obrigatorio' => true, 'completo' => true],
            ['nome' => 'valor', 'rotulo' => 'Valor', 'tipo' => 'number', 'obrigatorio' => true, 'dinheiro' => true],
            ['nome' => 'dataDespesa', 'rotulo' => 'Data da despesa', 'tipo' => 'date', 'obrigatorio' => true],
            ['nome' => 'categoria', 'rotulo' => 'Categoria', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => ['Aluguel', 'Energia', 'Agua', 'Funcionarios', 'Manutencao', 'Outros']],
            ['nome' => 'idAcademia', 'rotulo' => 'Academia', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Academia', 'id' => 'idAcademia', 'rotulo' => 'nome']],
        ],
    ],
    'relatorios' => [
        'titulo' => 'Relatorios Financeiros',
        'singular' => 'relatorio financeiro',
        'secao' => 'relatorios',
        'perfis' => ['ADMIN', 'GERENTE'],
        'somente_leitura_perfis' => ['ADMIN'],
        'tabela' => 'RelatorioFinanceiro',
        'id' => 'idRelatorio',
        'ordem' => 'idRelatorio DESC',
        'campos' => [
            ['nome' => 'mesReferencia', 'rotulo' => 'Mes de referencia', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => $opcoes_meses],
            ['nome' => 'anoReferencia', 'rotulo' => 'Ano de referencia', 'tipo' => 'number', 'obrigatorio' => true],
            ['nome' => 'idAcademia', 'rotulo' => 'Academia', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Academia', 'id' => 'idAcademia', 'rotulo' => 'nome']],
            ['nome' => 'idGerente', 'rotulo' => 'Gerente', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Usuario', 'id' => 'idUsuario', 'rotulo' => "CONCAT(nome, ' ', sobrenome)", 'filtro' => "perfil = 'GERENTE'"]],
            ['nome' => 'totalReceitas', 'rotulo' => 'Total de receitas', 'tipo' => 'number', 'somente_leitura' => true, 'dinheiro' => true],
            ['nome' => 'totalDespesas', 'rotulo' => 'Total de despesas', 'tipo' => 'number', 'somente_leitura' => true, 'dinheiro' => true],
            ['nome' => 'saldoFinal', 'rotulo' => 'Saldo final', 'tipo' => 'number', 'somente_leitura' => true, 'dinheiro' => true],
        ],
    ],
    'atendentes' => [
        'titulo' => 'Atendentes',
        'singular' => 'atendente',
        'secao' => 'atendentes',
        'perfis' => ['GERENTE'],
        'tabela' => 'Usuario',
        'id' => 'idUsuario',
        'ordem' => 'idUsuario DESC',
        'filtro_sql' => "perfil = 'ATENDENTE'",
        'valores_fixos' => ['perfil' => 'ATENDENTE'],
        'campos' => [
            ['nome' => 'nome', 'rotulo' => 'Nome', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'sobrenome', 'rotulo' => 'Sobrenome', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'cpf', 'rotulo' => 'CPF', 'tipo' => 'text', 'obrigatorio' => true],
            ['nome' => 'email', 'rotulo' => 'E-mail', 'tipo' => 'email', 'obrigatorio' => true],
            ['nome' => 'telefone', 'rotulo' => 'Telefone', 'tipo' => 'tel', 'obrigatorio' => true],
            ['nome' => 'senhaCriptografada', 'rotulo' => 'Senha', 'tipo' => 'password', 'obrigatorio' => true, 'tabela_listagem' => false],
        ],
    ],
    'suporte' => [
        'titulo' => 'Solicitacoes de Suporte',
        'singular' => 'solicitacao',
        'secao' => 'suporte',
        'perfis' => ['ADMIN', 'GERENTE', 'ATENDENTE', 'CLIENTE'],
        'tabela' => 'SolicitacaoSuporte',
        'id' => 'idSolicitacao',
        'ordem' => 'idSolicitacao DESC',
        'campos' => [
            ['nome' => 'descricao', 'rotulo' => 'Descricao', 'tipo' => 'textarea', 'obrigatorio' => true, 'completo' => true],
            ['nome' => 'status', 'rotulo' => 'Status', 'tipo' => 'select', 'obrigatorio' => true, 'opcoes' => ['Aberta', 'Em andamento', 'Resolvida'], 'ocultar_para_perfis' => ['GERENTE', 'ATENDENTE', 'CLIENTE']],
            ['nome' => 'dataAbertura', 'rotulo' => 'Data de abertura', 'tipo' => 'date', 'obrigatorio' => true, 'ocultar_para_perfis' => ['GERENTE', 'ATENDENTE', 'CLIENTE']],
            ['nome' => 'dataFechamento', 'rotulo' => 'Data de fechamento', 'tipo' => 'date', 'ocultar_para_perfis' => ['GERENTE', 'ATENDENTE', 'CLIENTE']],
            ['nome' => 'idUsuarioSolicitante', 'rotulo' => 'Usuario solicitante', 'tipo' => 'select', 'obrigatorio' => true, 'relacao' => ['tabela' => 'Usuario', 'id' => 'idUsuario', 'rotulo' => "CONCAT(nome, ' ', sobrenome, ' (', perfil, ')')"], 'ocultar_para_perfis' => ['GERENTE', 'ATENDENTE', 'CLIENTE']],
            ['nome' => 'idAdminResponsavel', 'rotulo' => 'Admin responsavel', 'tipo' => 'select', 'relacao' => ['tabela' => 'Usuario', 'id' => 'idUsuario', 'rotulo' => "CONCAT(nome, ' ', sobrenome)", 'filtro' => "perfil = 'ADMIN'"], 'ocultar_para_perfis' => ['GERENTE', 'ATENDENTE', 'CLIENTE']],
        ],
    ],
];
